version: "3.2"
services:
    web:
        image: flaskapp
        command: python -u app.py
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "5000:5000"
        volumes:
            - .:/todo
        environment:
            - MONGO_HOSTNAME=db
        networks:
            - webapp
    db:
        image: mongo
        volumes:
            - "/home/marcjones/Downloads/mongo_data:/data/db"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webapp
        ports:
            - 27017:27017
networks:
    webapp:
        attachable: true
