version: "3.2"
services:
    web:
        image: flaskapp
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
        volumes:
            - "~/scratch/content:/content"
        environment:
            - MONGO_HOSTNAME=db
        networks:
            - webapp
    db:
        image: mongo
        volumes:
            - "~/scratch/mongo_data:/data/db"
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        networks:
            - webapp
        ports:
            - 27017:27017
networks:
    webapp:
        attachable: true
