version: "3.2"
services:
    web:
        image: flaskapp
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
        volumes:
            - .:/todo
        environment:
            - MONGO_HOSTNAME=db
        networks:
            - webapp
    db:
        image: mongo
        volumes:
            - "/home/marcjones/Downloads/mongo_data:/data/db"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webapp
        ports:
            - 27017:27017
networks:
    webapp:
        attachable: true
