---
- hosts: all

  vars_files:
    - vars.yml

  tasks:

    - name: install git
      yum:
        name: git
        state: present

    - name: clone the webapp repository
      git:
        repo: "{{ webapp_git_repo }}"
        dest: /opt/aionplot

    - name: install Docker dependencies
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: add the Docker repo
      yum_repository:
        name: dockerrepo
        description: docker main repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        enabled: 1
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: install the Docker engine
      yum:
        name: docker-ce
      notify: restart docker daemon

    - name: enable the Docker service
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker daemon
      service:
        name: docker
        state: restarted
