---
- hosts: all

  vars_files:
    - vars.yml

  tasks:

    - name: copy across data files
      synchronize:
        src: "{{ LOCAL_DATA_DIR }}/"
        dest: "{{ SERVER_DATA_DIR }}"

    - name: run populator
      docker_container:
        name: populator
        image: "{{ AIONPLOT_POPULATOR_IMAGE }}"
        pull: yes
        volumes:
          -  "{{ SERVER_CONTENT_DIR }}:/content"
          -  "{{ SERVER_DATA_DIR }}:/data"
        networks:
          - name: webapp
        env:
          MONGO_DBADMIN_USERNAME: "{{ MONGO_DBADMIN_USERNAME }}"
          MONGO_DBADMIN_PASSWORD: "{{ MONGO_DBADMIN_PASSWORD }}"
          POPULATOR_DUMP_THRESHOLD: "{{ POPULATOR_DUMP_THRESHOLD }}"
        cleanup: True
        detach: False
